# Generated by Django 5.2.6 on 2026-03-23 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_remove_exercise_equipment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='equipment_photo',
            field=models.ImageField(blank=True, null=True, upload_to='exercise-equipment/'),
        ),
    ]
