# Generated by Django 5.2.6 on 2026-04-27 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0003_exercise_equipment_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exercise",
            name="type",
        ),
        migrations.AddField(
            model_name="exercise",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
