# Generated by Django 5.2.6 on 2026-03-25 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_routine_description_mealplan_mealitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='source_routine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_copies', to='workouts.routine'),
        ),
    ]
