# Generated by Django 5.2.6 on 2026-03-25 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_routine_source_routine'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='source_meal_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_plan_copies', to='workouts.mealplan'),
        ),
    ]
