# Generated by Django 6.0.2 on 2026-04-01 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0004_mealcategory_meal_category"),
        ("workouts", "0006_mealplan_source_meal_plan"),
    ]

    operations = []
