# Generated by Django 6.0.2 on 2026-04-01 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0007_merge_20260401_2015"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="meals/"),
        ),
        migrations.AddField(
            model_name="meal",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
