# Generated by Django 5.2.6 on 2026-05-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0009_merge_20260503_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='meal_type',
            field=models.CharField(blank=True, default='other', max_length=50),
        ),
    ]
