# Generated by Django 5.2.6 on 2026-05-06 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0011_meal_image_prompt_meal_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='image_prompt',
        ),
    ]
